# Generated by Django 4.2.21 on 2025-06-30 02:26

from django.db import migrations
from pgvector.django import VectorExtension

class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        VectorExtension(),
    ]
