# Generated by Django 4.2.21 on 2025-06-29 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('time_updated', models.DateTimeField(blank=True, null=True)),
                ('time_discovered', models.DateTimeField()),
                ('time_last_requested', models.DateTimeField(blank=True, null=True)),
                ('is_source', models.BooleanField(default=False)),
                ('robots_txt', models.TextField(blank=True, null=True)),
                ('time_last_checked_robots_txt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('time_updated', models.DateTimeField(blank=True, null=True)),
                ('time_discovered', models.DateTimeField()),
                ('time_last_requested', models.DateTimeField(blank=True, null=True)),
                ('is_source', models.BooleanField(default=False)),
                ('level', models.IntegerField(default=0)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.domain')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
