# Generated by Django 4.2.21 on 2025-07-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_enable_pgvector'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='is_redirect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webpage',
            name='is_redirect',
            field=models.BooleanField(default=False),
        ),
    ]
