# Generated by Django 4.2.21 on 2025-07-02 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_domain_is_redirect_webpage_is_redirect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_discovered', models.DateTimeField()),
                ('destination_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_domain', to='webpage.domain')),
                ('destination_webpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_webpage', to='webpage.webpage')),
                ('source_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_domain', to='webpage.domain')),
                ('source_webpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_webpage', to='webpage.webpage')),
            ],
        ),
    ]
