# Generated by Django 4.2.21 on 2025-07-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0005_domain_crawl_page_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='crawl_page',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='crawl_page_time_last_requested',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='crawl_page_type',
        ),
        migrations.AddField(
            model_name='webpage',
            name='page_type',
            field=models.CharField(default='html', max_length=50),
        ),
    ]
