# Generated by Django 4.2.21 on 2025-07-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0006_remove_domain_crawl_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='url',
            field=models.URLField(max_length=510),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='url',
            field=models.URLField(max_length=510),
        ),
    ]
