# Generated by Django 4.2.21 on 2025-07-07 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0007_alter_domain_url_alter_webpage_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='destination_domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrs_from', to='webpage.domain'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='destination_webpage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrs_from', to='webpage.webpage'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='source_domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrs_to', to='webpage.domain'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='source_webpage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrs_to', to='webpage.webpage'),
        ),
    ]
