# Generated by Django 4.2.21 on 2025-07-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0009_domain_tags_webpage_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='image',
            field=models.URLField(blank=True, max_length=510),
        ),
        migrations.AddField(
            model_name='webpage',
            name='image',
            field=models.URLField(blank=True, max_length=510),
        ),
    ]
