# Generated by Django 4.2.21 on 2025-07-10 19:07

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('organize_webpages', '0003_alter_thothtag_parents'),
        ('webpage', '0010_domain_image_webpage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='image',
            field=models.URLField(blank=True, max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='organize_webpages.ThothTaggedItem', to='organize_webpages.ThothTag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='image',
            field=models.URLField(blank=True, max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='organize_webpages.ThothTaggedItem', to='organize_webpages.ThothTag', verbose_name='Tags'),
        ),
    ]
