# Generated by Django 4.2.21 on 2025-07-12 17:21

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0011_alter_domain_image_alter_domain_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embeddings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('source_attribute', models.CharField()),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='webpage.domain')),
                ('webpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='webpage.webpage')),
            ],
        ),
    ]
