# Generated by Django 4.2.21 on 2025-07-14 04:51

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0012_embeddings'),
    ]

    operations = [
        TrigramExtension()
    ]
