# Generated by Django 4.2.21 on 2025-07-24 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0013_enable_trigram'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='time_published',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webpage',
            name='time_published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
