# Generated by Django 4.2.21 on 2025-07-07 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organize_webpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thothtag',
            name='is_top_level',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='thothtaggeditem',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='organize_webpages.thothtag'),
        ),
    ]
