# Generated by Django 4.2.21 on 2025-07-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize_webpages', '0002_thothtag_is_top_level_alter_thothtaggeditem_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thothtag',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', to='organize_webpages.thothtag'),
        ),
    ]
